// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xqnlnqqoobwybgcusqly.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhxbmxucXFvb2J3eWJnY3VzcWx5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5OTkwMDcsImV4cCI6MjA2NTU3NTAwN30.0J73ZGJ92uKLReBSp4SfzMrUSnBBY8ozK151MKMKT2w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);